"use client";

// Preview of the live FedEx report (composed from the real approved Findings) rendered
// through the Survey Studio editorial renderer. Generated by lib/studio/qa/fedex-report-generate.ts.
import { StudioReportDocument } from "@/app/components/studio/report/StudioReportDocument";
import { fedexPreviewDocument } from "../fedex-config";

export default function FedexReportPreview() {
  return (
    <div>
      <div data-no-print="true" style={{ display: "flex", gap: 12, padding: "10px 20px", borderBottom: "1px solid #E3E6EA", fontFamily: "system-ui", fontSize: 13, background: "#fff" }}>
        <span style={{ color: "#858D99" }}>FedEx report preview (live-composed)</span>
        <button type="button" onClick={() => window.print()} style={{ marginLeft: "auto", border: "1px solid #D7B87A", background: "transparent", color: "#8A6D2F", borderRadius: 6, padding: "4px 12px", fontSize: 12.5, cursor: "pointer" }}>Print / PDF</button>
      </div>
      <StudioReportDocument doc={fedexPreviewDocument} />
    </div>
  );
}
