"use client";

// ── Progressive states ───────────────────────────────────────────────────────
// The in-between states an intelligence platform lives in: work is running, or
// advancing through stages, or being generated by the model. Distinct from the
// skeleton loading state (content arriving) — these communicate *ongoing work*
// with a clear sense of how far along it is.

import { Icon } from "./icons";

// ── ProgressBar ──────────────────────────────────────────────────────────────
// A determinate bar with optional label and value. `indeterminate` shows a
// looping sweep for work whose duration is unknown.
export function ProgressBar({
  value = 0, label, showValue = true, indeterminate = false, tone = "accent",
}: {
  value?: number;
  label?: React.ReactNode;
  showValue?: boolean;
  indeterminate?: boolean;
  tone?: "accent" | "navy" | "success";
}) {
  const fill = tone === "navy" ? "var(--brand-navy)" : tone === "success" ? "#5C8560" : "var(--accent-gold)";
  return (
    <div>
      {(label || showValue) && (
        <div className="flex items-center justify-between mb-1.5">
          {label && <span className="text-xs font-medium" style={{ color: "var(--text-secondary)" }}>{label}</span>}
          {showValue && !indeterminate && <span className="fx-tabular-nums text-xs font-semibold" style={{ color: "var(--text-tertiary)" }}>{Math.round(value)}%</span>}
        </div>
      )}
      <div className="h-1.5 rounded-full overflow-hidden relative" style={{ background: "var(--surface-sunken)" }}>
        {indeterminate ? (
          <div className="absolute inset-y-0 rounded-full fx-indeterminate" style={{ width: "40%", background: fill }} />
        ) : (
          <div className="h-full rounded-full transition-[width] duration-500 ease-out" style={{ width: `${Math.min(100, Math.max(0, value))}%`, background: fill }} />
        )}
      </div>
    </div>
  );
}

// ── ProgressSteps ────────────────────────────────────────────────────────────
// A vertical checklist of stages an item moves through — done / active /
// pending. The analyst-facing way to show "where in the pipeline is this?"
// (collect → analyse → report → conclude), with the active step called out.
export type StepState = "done" | "active" | "pending";

export function ProgressSteps({
  steps, className = "",
}: {
  steps: { label: React.ReactNode; description?: React.ReactNode; state: StepState }[];
  className?: string;
}) {
  return (
    <ol className={className}>
      {steps.map((s, i) => {
        const last = i === steps.length - 1;
        return (
          <li key={i} className="flex gap-3">
            <div className="flex flex-col items-center">
              <span
                className="flex items-center justify-center rounded-full flex-shrink-0"
                style={{
                  width: 20, height: 20,
                  background: s.state === "done" ? "#5C8560" : s.state === "active" ? "var(--accent-gold)" : "var(--surface-sunken)",
                  color: s.state === "pending" ? "var(--text-disabled)" : "#FFFFFF",
                  border: s.state === "pending" ? "1px solid var(--border-default)" : "none",
                }}
              >
                {s.state === "done" ? <Icon.check size={12} strokeWidth={2.5} />
                  : s.state === "active" ? <span className="w-1.5 h-1.5 rounded-full bg-white" />
                  : <span className="fx-tabular-nums text-[10px] font-bold" style={{ color: "var(--text-tertiary)" }}>{i + 1}</span>}
              </span>
              {!last && <span className="w-px flex-1 my-1" style={{ background: s.state === "done" ? "#5C8560" : "var(--border-default)", minHeight: 16 }} />}
            </div>
            <div className={last ? "" : "pb-4"}>
              <p className="text-sm font-semibold leading-tight" style={{ color: s.state === "pending" ? "var(--text-tertiary)" : "var(--text-primary)" }}>{s.label}</p>
              {s.description && <p className="text-xs mt-0.5 leading-relaxed" style={{ color: "var(--text-tertiary)" }}>{s.description}</p>}
            </div>
          </li>
        );
      })}
    </ol>
  );
}

// ── GenerationProgress ───────────────────────────────────────────────────────
// The "the model is working" state — an AI generation in flight. Sparkle mark,
// a live status line, and an indeterminate (or determinate) bar. Use while
// Intelligence, a report, or a conclusion is being generated.
export function GenerationProgress({
  title = "Generating intelligence", status, value, steps,
}: {
  title?: React.ReactNode;
  /** The live status line, e.g. "Analysing 1,284 responses…". */
  status?: React.ReactNode;
  /** Omit for an indeterminate bar; provide 0–100 for determinate. */
  value?: number;
  /** Optional stage list shown beneath the bar. */
  steps?: { label: React.ReactNode; state: StepState }[];
}) {
  return (
    <div className="border p-5" style={{ borderRadius: "var(--radius-panel)", borderColor: "#E7DCC2", background: "linear-gradient(135deg, #FCF8EF 0%, #FFFFFF 60%)" }}>
      <div className="flex items-center gap-2.5">
        <span className="inline-flex items-center justify-center w-7 h-7 rounded-lg fx-pulse" style={{ background: "#F2E6C8", color: "#8A6D2F" }} aria-hidden>
          <Icon.sparkles size={16} />
        </span>
        <div className="min-w-0">
          <p className="text-sm font-bold" style={{ color: "var(--text-primary)" }}>{title}</p>
          {status && <p className="text-xs mt-0.5 truncate" style={{ color: "var(--text-secondary)" }}>{status}</p>}
        </div>
      </div>
      <div className="mt-4">
        <ProgressBar value={value} indeterminate={value === undefined} showValue={value !== undefined} tone="accent" />
      </div>
      {steps && steps.length > 0 && (
        <ul className="flex flex-wrap gap-x-4 gap-y-1 mt-3">
          {steps.map((s, i) => (
            <li key={i} className="inline-flex items-center gap-1.5 text-[11px]" style={{ color: s.state === "pending" ? "var(--text-disabled)" : "var(--text-secondary)" }}>
              {s.state === "done" ? <span style={{ color: "#5C8560" }}><Icon.check size={12} strokeWidth={2.5} /></span>
                : s.state === "active" ? <span className="w-1.5 h-1.5 rounded-full fx-pulse" style={{ background: "var(--accent-gold)" }} />
                : <span className="w-1.5 h-1.5 rounded-full" style={{ background: "var(--border-strong)" }} />}
              {s.label}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
