// ── Live FedEx Report generation (QA) — the exact production compose pipeline ──
// Reads the REAL FedEx Study + its human-approved Findings (read-only), runs the REAL
// composer → verifier → editorial document builder, and writes the resulting
// StudyReportDocument to a preview module for in-browser inspection. It does NOT persist a
// study_reports row here; everything else is the production path. Run 1–3 times to inspect
// run-to-run consistency.
//
//   npx tsx lib/studio/qa/fedex-report-generate.ts [runs]

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { resolveReportInput, composeReportDocument } from "@/lib/studio/report/report-service";
import type { AuthedUser } from "@/lib/auth-server";
import type { StudyReportDocument } from "@/lib/studio/report/report-document";

try {
  for (const line of readFileSync(path.join(process.cwd(), ".env.local"), "utf8").split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
  }
} catch { /* env may already be present */ }

const FEDEX_STUDY_ID = "e398f93f-461d-47c7-94cc-6f1352716ae6";
const session = { workEmail: "edesbois@yahoo.co.uk", role: "admin" } as unknown as AuthedUser;
const RUNS = Math.max(1, Math.min(3, Number(process.argv[2] ?? 1)));

function summarise(doc: StudyReportDocument) {
  const moduleKinds = doc.pages.flatMap((p) => p.modules.map((m) => m.kind));
  console.log(`  coverMode=${doc.coverMode} · pages=${doc.pages.length} · modules=[${moduleKinds.join(", ")}]`);
  for (const p of doc.pages) {
    console.log(`   [${p.archetype}] ${p.headline}`);
    for (const m of p.modules) {
      if (m.kind === "key-numbers") console.log(`       key-numbers: ${m.stats.map((s) => `${s.value} ${s.label}`).join(" · ")}`);
      if (m.kind === "distribution") console.log(`       distribution: ${m.question} → ${m.options.map((o) => `${o.label} ${o.pct}%${o.highlight ? "◀" : ""}`).join(", ")}`);
      if (m.kind === "audience-comparison") console.log(`       audience: ${m.caption} → ${m.points.map((pt) => `${pt.label} ${pt.pct != null ? pt.pct + "%" : pt.value}`).join(", ")}`);
      if (m.kind === "hero-stat") console.log(`       hero: ${m.stat.value} ${m.stat.label}`);
      if (m.kind === "finding-callout") console.log(`       callout: ${m.title}`);
      if (m.kind === "implications") for (const it of m.items) console.log(`       → ${it}`);
    }
  }
}

async function main() {
  const r = await resolveReportInput(session, FEDEX_STUDY_ID);
  if (r.access !== "ok" || !r.input || !r.governance) { console.error("could not resolve report input:", r.access); process.exit(1); }
  console.log(`\n=== FedEx report input: ${r.input.findings.length} approved findings · ${r.input.methodology.totalResponses} responses · markets: ${r.input.methodology.markets.join(", ") || "(none)"} · audience comparisons available: ${r.governance.segmentComparisons.size} ===`);

  let last: StudyReportDocument | null = null;
  for (let run = 1; run <= RUNS; run++) {
    const out = await composeReportDocument(r.input, r.governance);
    if (!out.ok || !out.document) { console.error(`\nRUN ${run} FAILED:`, out.error, out.reasons ?? ""); continue; }
    console.log(`\n=== RUN ${run} ===`);
    summarise(out.document);
    last = out.document;
  }
  if (!last) process.exit(1);

  const outPath = path.join(process.cwd(), "app/survey-studio/reports-preview/fedex-config.ts");
  writeFileSync(outPath, `// AUTO-GENERATED by lib/studio/qa/fedex-report-generate.ts — a real editorial report composed\n// from the live FedEx approved Findings. Preview-only; the production path persists to study_reports.\nimport type { StudyReportDocument } from "@/lib/studio/report/report-document";\nexport const fedexPreviewDocument: StudyReportDocument = ${JSON.stringify(last, null, 2)} as StudyReportDocument;\n`);
  console.log(`\nGenerated preview → app/survey-studio/reports-preview/fedex-config.ts · Inspect at: /survey-studio/reports-preview/fedex\n`);
}
main().catch((e) => { console.error(e); process.exit(1); });
