// ── Slice A QA — FedEx Executive Page 1 (exact production pipeline) ──────────
// Reads the REAL FedEx Study + approved Findings (read-only), runs the REAL composer → verify
// → Governed Visual Evidence → Executive-page builder, and writes the resulting governed
// ExecutiveReportDocument to a preview module. No hand-authored content; no FedEx-specific
// logic. It does NOT persist a study_reports row.
//
//   npx tsx lib/studio/qa/fedex-page1-generate.ts

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { resolveReportInput, composeExecutivePage } from "@/lib/studio/report/report-service";
import { assessRichness } from "@/lib/studio/report/richness";
import type { AuthedUser } from "@/lib/auth-server";
import type { ExecutiveReportDocument } from "@/lib/studio/report/executive-page";

try {
  for (const line of readFileSync(path.join(process.cwd(), ".env.local"), "utf8").split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
  }
} catch { /* env may already be present */ }

const FEDEX_STUDY_ID = "e398f93f-461d-47c7-94cc-6f1352716ae6";
const session = { workEmail: "edesbois@yahoo.co.uk", role: "admin" } as unknown as AuthedUser;

function summarise(doc: ExecutiveReportDocument) {
  console.log(`  kind=${doc.kind} · richness=${doc.richness} · cover=${doc.coverMode}`);
  console.log(`  OBJECTIVE: ${doc.identity.objective}`);
  console.log(`  HEADLINE: ${doc.headline}`);
  console.log(`  HERO MODE: ${doc.hero.mode}`);
  if (doc.hero.primary) console.log(`    primary: ${doc.hero.primary.value} ${doc.hero.primary.label}`);
  if (doc.hero.tension) console.log(`    tension: ${doc.hero.tension.value} ${doc.hero.tension.label}`);
  console.log(`  WHAT WE FOUND: ${doc.whatWeFound}`);
  for (const m of doc.modules) {
    if (m.kind === "key-numbers") console.log(`  KEY NUMBERS: ${m.stats.map((s) => `${s.value} ${s.label}`).join(" · ")}`);
    if (m.kind === "distribution") console.log(`  DISTRIBUTION: ${m.question} (n=${m.n}) → ${m.options.map((o) => `${o.label} ${o.pct}%${o.highlight ? "◀" : ""}`).join(", ")}`);
  }
  if (doc.bottomLine) console.log(`  BOTTOM LINE (${doc.bottomLine.form}): ${doc.bottomLine.text}`);
  console.log(`  METHODOLOGY: ${doc.methodology}`);
}

async function main() {
  const r = await resolveReportInput(session, FEDEX_STUDY_ID);
  if (r.access !== "ok" || !r.input || !r.governance) { console.error("could not resolve report input:", r.access); process.exit(1); }
  const richness = assessRichness(r.input, r.governance);
  console.log(`\n=== FedEx input: ${r.input.findings.length} findings · ${r.input.methodology.totalResponses} responses · markets: ${r.input.methodology.markets.join(", ")} ===`);
  console.log(`=== Richness: ${richness.level} · budget ${richness.recommendedPageBudget} · visuals [${richness.availableVisuals.join(", ")}] · ${richness.reasons.join("; ")} ===\n`);

  const out = await composeExecutivePage(r.input, r.governance);
  if (!out.ok || !out.document) { console.error("FAILED:", out.error, out.reasons ?? ""); process.exit(1); }
  summarise(out.document);

  const outPath = path.join(process.cwd(), "app/survey-studio/reports-preview/fedex-page1-config.ts");
  writeFileSync(outPath, `// AUTO-GENERATED by lib/studio/qa/fedex-page1-generate.ts — a real governed Executive page\n// composed from the live FedEx approved Findings. Preview-only.\nimport type { ExecutiveReportDocument } from "@/lib/studio/report/executive-page";\nexport const fedexPage1Document: ExecutiveReportDocument = ${JSON.stringify(out.document, null, 2)} as ExecutiveReportDocument;\n`);
  console.log(`\nGenerated → app/survey-studio/reports-preview/fedex-page1-config.ts · Inspect at: /survey-studio/reports-preview/fedex-page1\n`);
}
main().catch((e) => { console.error(e); process.exit(1); });
