// ── Slice B QA — FedEx two-page infographic report (exact production pipeline) ──
// Reads the REAL FedEx Study + approved Findings (read-only), runs the REAL composers → verify →
// governed builders for BOTH pages, and writes the resulting documents to a preview module.
// No hand-authored content; no FedEx-specific logic; nothing persisted.
//
//   npx tsx lib/studio/qa/fedex-infographic-generate.ts

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { resolveReportInput, composeInfographicReport } from "@/lib/studio/report/report-service";
import type { AuthedUser } from "@/lib/auth-server";

try {
  for (const line of readFileSync(path.join(process.cwd(), ".env.local"), "utf8").split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
  }
} catch { /* env may already be present */ }

const FEDEX_STUDY_ID = "e398f93f-461d-47c7-94cc-6f1352716ae6";
const session = { workEmail: "edesbois@yahoo.co.uk", role: "admin" } as unknown as AuthedUser;

async function main() {
  const r = await resolveReportInput(session, FEDEX_STUDY_ID);
  if (r.access !== "ok" || !r.input || !r.governance) { console.error("could not resolve report input:", r.access); process.exit(1); }
  const out = await composeInfographicReport(r.input, r.governance);
  if (!out.ok || !out.pages) { console.error("FAILED:", out.error, out.reasons ?? ""); process.exit(1); }

  const ex = out.pages.executive, evd = out.pages.evidence;
  console.log(`\n=== REPORT: richness=${out.richness!.level} · budget ${out.richness!.recommendedPageBudget} · pages=${evd ? 2 : 1} · reportStoryComplete=${out.reportStoryComplete} ===`);
  console.log(`unused governed distributions: ${out.unusedGovernedDistributions!.map((u) => `"${u.question}" (${u.reason})`).join("; ") || "none"}`);

  console.log(`\n--- PAGE 1 (Executive, unchanged A.4) ---`);
  console.log(`  HEADLINE: ${ex.headline}`);
  console.log(`  HERO: ${ex.hero.mode}${ex.hero.primary ? ` ${ex.hero.primary.value} ${ex.hero.primary.label}` : ""}${ex.hero.tension ? ` / ${ex.hero.gap?.value} / ${ex.hero.tension.value} ${ex.hero.tension.label}` : ""}`);

  if (evd) {
    console.log(`\n--- PAGE 2 (Evidence & Opportunity) ---`);
    console.log(`  HEADLINE: ${evd.headline}`);
    console.log(`  INTRO: ${evd.intro}`);
    for (const m of evd.modules) {
      if (m.kind === "segment-comparison") console.log(`  SEGMENT [${m.mode}] ${m.caption} → ${m.points.map((p) => `${p.label}=${p.value ?? p.pct + "%"}`).join(", ")}`);
      if (m.kind === "ranked-distribution") console.log(`  RANKED: ${m.question} → ${m.options.map((o) => `${o.label} ${o.pct}%${o.highlight ? "◀" : ""}`).join(", ")}${m.leadNote ? ` [${m.leadNote}]` : ""}`);
    }
    console.log(`  WHAT THIS MEANS: ${evd.implications.map((t, i) => `\n    ${i + 1}. ${t}`).join("")}`);
    console.log(`  METHODOLOGY: ${evd.methodology}`);
  }

  const outPath = path.join(process.cwd(), "app/survey-studio/reports-preview/fedex-infographic-config.ts");
  writeFileSync(outPath, `// AUTO-GENERATED by lib/studio/qa/fedex-infographic-generate.ts — the real governed two-page\n// FedEx infographic report. Preview-only.\nimport type { ExecutiveReportDocument } from "@/lib/studio/report/executive-page";\nimport type { EvidenceReportDocument } from "@/lib/studio/report/evidence-page";\nexport const fedexExecutiveDocument: ExecutiveReportDocument = ${JSON.stringify(ex, null, 2)} as ExecutiveReportDocument;\nexport const fedexEvidenceDocument: EvidenceReportDocument | null = ${JSON.stringify(evd, null, 2)} as EvidenceReportDocument | null;\nexport const fedexReportComplete = ${out.reportStoryComplete};\n`);
  console.log(`\nGenerated → app/survey-studio/reports-preview/fedex-infographic-config.ts · Inspect at: /survey-studio/reports-preview/fedex-infographic\n`);
}
main().catch((e) => { console.error(e); process.exit(1); });
