// The Research Plan — the project's methodology briefing (docs/research-plan-blueprint.md).
// Shared types + presentation helpers. The plan is generated by
// analyseResearchPlan, stored as a `research_plan` output on research_summaries,
// and rendered by the Research Plan surface. It carries method SUITABILITY and
// EXPECTED CONTRIBUTION only — never "confidence" (that is Analysis's word, from
// real evidence). Per-theme `required_evidence` is the yardstick Analysis later
// reads against to report methodology execution completeness (planned vs collected).

export type EvidenceMethod = "conversation" | "survey" | "document" | "news";
export type MethodSuitability = "Well suited" | "Partly suited" | "Not suited";
export type Coverage = "strong" | "partial" | "none";

export const EVIDENCE_METHODS: EvidenceMethod[] = ["conversation", "survey", "document", "news"];
export const METHOD_LABEL: Record<EvidenceMethod, string> = {
  conversation: "Conversation Intelligence",
  survey: "Survey",
  document: "Research Library",
  news: "News",
};

// One method's consultancy brief — why it's recommended, its role, what it will
// contribute, what it can't establish, and what the client gets. No confidence.
export type RecommendedMethod = {
  method: EvidenceMethod;
  recommended: boolean;
  suitability: MethodSuitability;
  why_recommended: string;
  role: string;
  expected_contribution: string;
  evidence_requirements: string;
  limitations: string;
  expected_outputs: string;
  available: boolean;
  availability_note: string | null;
};

// A checkable evidence requirement for a theme — structured so Analysis can later
// compare planned vs collected.
export type RequiredEvidence = { method: EvidenceMethod; description: string; rough_target: string | null };

export type EvidenceTheme = {
  theme: string;                 // short Title Case — becomes a Research Aspect
  description: string;
  best_methods: EvidenceMethod[];
  required_evidence: RequiredEvidence[];
};

export type CoverageCell = { theme: string; method: EvidenceMethod; coverage: Coverage };
export type PlanGap = { theme: string | null; missing: "method" | "source"; message: string; recommended_action: string };

// The conversation searches the plan WOULD create (Phase 2 compiles the actual
// Search Strategy at creation time; Phase 1 states the intent).
export type ConversationIntent = { theme: string; research_question: string; search_focus: string; sources: string[] };

export type MethodConfigs = {
  conversation: ConversationIntent[];
  survey: { recommended: boolean; brief: string; themes: string[]; suggested_target: string | null; markets: string[] } | null;
  document: { recommended: boolean; brief: string; looking_for: string[] } | null;
  news: { recommended: boolean; brief: string; available: false } | null;
};

export type ResearchPlan = {
  objective: string;
  hypothesis: string | null;
  assumptions: string[];
  methodology: { recommended_methods: RecommendedMethod[]; approach: string; advisor_note: string };
  evidence_themes: EvidenceTheme[];
  method_configs: MethodConfigs;
  expected_coverage: CoverageCell[];
  gaps: PlanGap[];
  expected_outputs: string[];
  remaining_limitations: string[];
  generated_at: string;
  edited: boolean;
  model: string;
};

export const SUITABILITY_TONE: Record<MethodSuitability, { ink: string; bg: string; border: string }> = {
  "Well suited":   { ink: "#3F5D42", bg: "#EEF3EC", border: "#D3E0D0" },
  "Partly suited": { ink: "var(--accent-ink)", bg: "var(--accent-wash)", border: "#ECDCB8" },
  "Not suited":    { ink: "var(--text-tertiary)", bg: "var(--surface-sunken)", border: "var(--border-subtle)" },
};
