"use client";

// Slice A preview — the live-composed FedEx Executive Page 1, rendered through the real
// governed Executive-page architecture (no hand-authored data). Generated by
// lib/studio/qa/fedex-page1-generate.ts.
import { ExecutiveReportPage } from "@/app/components/studio/report/ExecutiveReportPage";
import { fedexPage1Document } from "../fedex-page1-config";

export default function FedexPage1Preview() {
  return (
    <div>
      <div data-no-print="true" style={{ display: "flex", gap: 12, padding: "10px 20px", borderBottom: "1px solid #E3E6EA", fontFamily: "system-ui", fontSize: 13, background: "#fff" }}>
        <span style={{ color: "#858D99" }}>FedEx Executive Page 1 (live-composed · Slice A)</span>
        <button type="button" onClick={() => window.print()} style={{ marginLeft: "auto", border: "1px solid #D7B87A", background: "transparent", color: "#8A6D2F", borderRadius: 6, padding: "4px 12px", fontSize: 12.5, cursor: "pointer" }}>Print / PDF</button>
      </div>
      <div style={{ padding: "24px 0", background: "#F4F5F7" }}>
        <ExecutiveReportPage doc={fedexPage1Document} />
      </div>
    </div>
  );
}
