// ── Fanometrix Analytical Core — governance rule registry (data) ──────────────
// One entry per governance rule. Authored ONCE here; validators.ts and
// prompt-fragments.ts project each rule to a deterministic/heuristic check and a
// prompt fragment. `legacy` + `equivalence` record how it relates to current
// production governance (detail in legacy-map.ts). Stage 2 is additive/shadowed.

import type { GovernanceRule } from "./types";

export const GOVERNANCE_RULES: GovernanceRule[] = [
  {
    id: "unsupported_causation",
    title: "Unsupported causation",
    category: "causality",
    description: "CANONICAL (Decision, §15/§16/§21): causal claims are NOT universally prohibited — they are permitted only where the study design and evidence are governed as capable of causal inference (ctx.causalSupportEstablished). Otherwise, causal language (incl. preference/association/sequence rewritten as causation) is a blocking violation. Lexical absence never proves safety; the safe default is unsupported → blocking.",
    standardRef: ["§15", "§16", "§21"],
    severity: "blocking",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["any"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "study-analysis.ts BANNED_PATTERNS", note: "hard-rejects the causal word (over-broad vs canonical)" },
      { system: "research_projects", location: "matrix.ts causal row + review-detectors.ts CAUSAL", note: "admissibility-graded (closer to canonical) + surface flag" },
    ],
    equivalence: "canonical_supersedes",
    futureEvidence: "A causal claim is allowed only once governed causal-support evidence exists (ctx.causalSupportEstablished).",
  },
  {
    id: "unsupported_trend",
    title: "Unsupported trend / change over time",
    category: "temporal",
    description: "CANONICAL (Decision 6, §11.4): change language is governed by EVIDENCE STATE, not a fixed word list. Permitted only where ctx.changeState is 'comparable_change' (any change word) or 'trend' (the word 'trend'). For 'dataset_difference' or no governed state, change language is a blocking violation. The heuristic vocabulary is broadened (stricter than legacy). Stage 2.1 does not compute the change test.",
    standardRef: ["§11.4"],
    severity: "blocking",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["any"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "study-analysis.ts BANNED_PATTERNS temporal", note: "rejects all change-over-time unconditionally; misses 'collapsed/shrank'; report vs analysis conflict on 'improve'" },
      { system: "research_projects", location: "matrix.ts temporal row", note: "permits temporal for continuous-collection kinds" },
    ],
    equivalence: "canonical_supersedes",
    futureEvidence: "Change language lifted only with governed changeState (comparable_change/trend); the change test is a later stage (Decision 6).",
  },
  {
    id: "aggregate_to_respondent_inference",
    title: "Aggregate → respondent-level inference",
    category: "respondent_inference",
    description: "CANONICAL (Decision 10, §14/§15): respondent-level relationship language is allowed ONLY when governed respondent-level evidence supports the relationship (ctx.hasRespondentEvidence). Aggregate distributions can never establish it. Association may be allowed with respondent evidence; a CAUSAL reading of that relationship remains separately prohibited. Consolidates the two divergent legacy Studio pattern sets.",
    standardRef: ["§14", "§15"],
    severity: "blocking",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["respondent_level", "quantitative_survey"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "study-analysis.ts RESPONDENT_CORRELATION (rejects) + survey-findings-engine.ts CORRELATION_BANNED (throws)", note: "two different lists/enforcement — consolidated here" },
    ],
    equivalence: "canonical_supersedes",
    futureEvidence: "Allowed only when governed respondent-vector relationship evidence exists (Decision 10). Default: prohibited.",
  },
  {
    id: "unsupported_statistical_language",
    title: "Unsupported statistical-significance language",
    category: "statistical_language",
    description: "CANONICAL (Decision 2, §11.2/§12): 'significant'/'statistically significant' (and 'significant difference/increase', p-values, margin of error, confidence interval) are reserved for FORMAL statistical significance and require ctx.statisticalAssessment.status === 'supported'. Without it, statistical-significance wording is a blocking violation.",
    standardRef: ["§11.2", "§12"],
    severity: "blocking",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["any"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "study-analysis.ts significance cluster (allows 'significant portion')" },
      { system: "reports", location: "report-domain.ts REPORT_SIGNIFICANCE (bans the word entirely — over-broad vs canonical)" },
      { system: "research_projects", location: "matrix.ts magnitude row", note: "no word-ban; governs magnitude by evidence kind" },
    ],
    equivalence: "canonical_supersedes",
  },
  {
    id: "imprecise_significance_wording",
    title: "Imprecise 'significant' wording",
    category: "statistical_language",
    description: "CANONICAL (Decision 2): using 'significant' to merely mean large/important/material/notable (e.g. 'a significant proportion') is a WORDING issue — the word is reserved for statistical significance. Advisory: correct the wording (use 'large'/'notable'/an exact figure), do not read it as a statistical result.",
    standardRef: ["§11.2", "§12"],
    severity: "advisory",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["any"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "reports", location: "report-domain.ts REPORT_SIGNIFICANCE (bans the bare word — canonical downgrades to advisory wording)" },
    ],
    equivalence: "canonical_supersedes",
  },
  {
    id: "cross_question_arithmetic",
    title: "Cross-question arithmetic",
    category: "arithmetic",
    description: "Percentages from different questions must never be summed into a combined respondent share (Benchmark 001: 36.5% + 32.8% ≠ 69.3%). Detected from structured Result provenance and, heuristically, from prose.",
    standardRef: ["§9"],
    severity: "blocking",
    enforcement: "deterministic",
    applicability: { evidenceTypes: ["quantitative_survey"], scope: ["result", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "study-analysis.ts CROSS_Q_MAGNITUDE (prose, gated on ≥2 cited questions)" },
    ],
    equivalence: "studio_only",
  },
  {
    id: "invalid_semantic_grouping",
    title: "Invalid semantic grouping",
    category: "semantic_grouping",
    description: "A declared derived grouping must be within one compatible measurement, have ≥2 components, an accurate label and a coherent parent construct, with no double counting. Stage 2 validates declared grouping METADATA; it does not generate groupings, and cannot judge semantic coherence (that stays with the benchmark's declared allowed/forbidden lists).",
    standardRef: ["§7", "§8", "§9"],
    severity: "blocking",
    enforcement: "deterministic",
    applicability: { evidenceTypes: ["quantitative_survey"], scope: ["result"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "study-analysis.ts SHARE_AS_SENTIMENT (grouped share ≠ sentiment)" },
    ],
    equivalence: "new",
  },
  {
    id: "claim_exceeds_evidence",
    title: "Claim exceeds evidence",
    category: "claim_strength",
    description: "CANONICAL (§20/§21): claim strength must not exceed evidence strength. Uses the canonical, product-agnostic Evidence.contribution field (generalised RP taxonomy) — NOT RP-only sourceMeta. A causal/predictive claim requires ≥2 distinct contribution kinds or a supported statistical test.",
    standardRef: ["§20", "§21"],
    severity: "blocking",
    enforcement: "deterministic",
    applicability: { evidenceTypes: ["any"], scope: ["finding"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "research_projects", location: "types.ts ASSERTION_DEMAND + matrix.ts combination rule 6.1" },
    ],
    equivalence: "rp_only",
  },
  {
    id: "preference_to_outcome_leap",
    title: "Preference → outcome leap",
    category: "recommendation_outcome",
    description: "CANONICAL (§16): a measured preference/expectation/intention does not establish a behavioural or commercial OUTCOME ('X will improve Y'). This is an evidence-invalid claim, so it is BLOCKING unless ctx.outcomeEvidenceEstablished. Kept distinct from generic causality (fires even with no explicit causal verb).",
    standardRef: ["§16", "§35"],
    severity: "blocking",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["any"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "research_projects", location: "review-detectors.ts OUTCOME + analyseExecutiveReport invented-outcome (surface-only)" },
      { system: "studio", location: "analysis-quality.ts prescription drop", note: "folded into prescription hard-drop" },
    ],
    equivalence: "conflict",
  },
  {
    id: "unsupported_recommendation_outcome",
    title: "Unsupported recommendation outcome",
    category: "recommendation_outcome",
    description: "A recommendation must not claim an outcome beyond the evidence; where an action is said to produce an outcome, that outcome relationship must have been measured (Decision 8). Recommendations themselves are legitimate — this flags the unsupported action→outcome leap.",
    standardRef: ["§35"],
    severity: "advisory",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["any"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "analysis-quality.ts PRESCRIPTION_MARKERS (hard-drop)" },
      { system: "research_projects", location: "analyseExecutiveReport.ts recommendation discipline (prompt-only)" },
    ],
    equivalence: "conflict",
  },
  {
    id: "invalid_reference",
    title: "Invalid / fabricated reference",
    category: "references",
    description: "Analytical prose or a Finding must not cite evidence/reference ids absent from the governed evidence set. Generalises clampReferences (RP) and Studio ref resolution/stripping.",
    standardRef: ["§22"],
    severity: "blocking",
    enforcement: "deterministic",
    applicability: { evidenceTypes: ["any"], scope: ["prose", "finding"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "research_projects", location: "validate-references.ts clampReferences" },
      { system: "studio", location: "study-analysis.ts makeRefResolver / containsInlineRef" },
    ],
    equivalence: "equivalent",
  },
  {
    id: "unsupported_number",
    title: "Unsupported number",
    category: "grounding",
    description: "A number stated in analytical prose must belong to the governed evidence set. Generalises Studio unsupportedNumbers and RP percentage-trace.",
    standardRef: ["§3.2", "§22"],
    severity: "blocking",
    enforcement: "deterministic",
    applicability: { evidenceTypes: ["any"], scope: ["prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "reports", location: "report-domain.ts unsupportedNumbers (STAT_TOKEN)" },
      { system: "research_projects", location: "review-detectors.ts percentage-trace" },
    ],
    equivalence: "equivalent",
  },
  {
    id: "comparison_evidence_insufficiency",
    title: "Comparison evidence insufficiency",
    category: "comparison",
    description: "A comparative claim must cite evidence for all sides of the comparison. Generalises Studio's comparison firewall (≥2 refs). Full statistical comparability is a later stage.",
    standardRef: ["§11"],
    severity: "blocking",
    enforcement: "deterministic",
    applicability: { evidenceTypes: ["quantitative_survey", "any"], scope: ["result", "finding"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "study-analysis.ts comparison firewall (≥2 refs / one question / ≥2 surveys)" },
      { system: "research_projects", location: "matrix.ts comparative row" },
    ],
    equivalence: "stricter_in_studio",
  },
  {
    id: "sample_composition_not_popularity",
    title: "Sample composition ≠ popularity / priority",
    category: "sample_composition",
    description: "Share of responses / collection volume must not be described as audience popularity, value or priority unless the evidence supports that construct.",
    standardRef: ["§11.1", "§34"],
    severity: "advisory",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["quantitative_survey", "conversation"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "research_projects", location: "analyseSurvey/Conversation/ExecutiveReport (prompt-only, 3 divergent copies)" },
      { system: "studio", location: "study-analysis.ts priority-from-share regex" },
    ],
    equivalence: "conflict",
  },
  {
    id: "overstated_leadership",
    title: "Overstated leadership",
    category: "claim_strength",
    description: "Being numerically first does not license 'dominant / clear winner / overwhelming'. Heuristic prose flag; precise adjudication needs the lead size (Benchmark 001 MUST-NOT-SAY #1).",
    standardRef: ["§5", "§10"],
    severity: "advisory",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["quantitative_survey"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "studio", location: "executive-compose.ts DOMINANCE_MIN_LEAD_PP (structural) + headline precision prompt" },
    ],
    equivalence: "stricter_in_studio",
  },
  {
    id: "false_construct_contradiction",
    title: "False construct contradiction",
    category: "comparison",
    description: "Two measures framed as contradictory only contradict if they measure the same construct in the same population (RP construct-comparability). Heuristic surface flag.",
    standardRef: ["§18"],
    severity: "advisory",
    enforcement: "heuristic",
    applicability: { evidenceTypes: ["any"], scope: ["finding", "prose"] },
    hasValidator: true, hasPromptFragment: true,
    legacy: [
      { system: "research_projects", location: "review-detectors.ts framesConstructContradiction + executive-report-review.ts" },
    ],
    equivalence: "rp_only",
  },
];

const BY_ID = new Map(GOVERNANCE_RULES.map((r) => [r.id, r]));
export function getRule(id: string): GovernanceRule | undefined { return BY_ID.get(id); }
export type RuleId = (typeof GOVERNANCE_RULES)[number]["id"];
