// AUTO-GENERATED by lib/studio/qa/fedex-infographic-generate.ts — the real governed two-page
// FedEx infographic report. Preview-only.
import type { ExecutiveReportDocument } from "@/lib/studio/report/executive-page";
import type { EvidenceReportDocument } from "@/lib/studio/report/evidence-page";
export const fedexExecutiveDocument: ExecutiveReportDocument = {
  "kind": "studio-exec-report-v1",
  "masthead": {
    "brand": "FANOMETRIX",
    "kicker": "Survey Study Report"
  },
  "identity": {
    "title": "FedEx UCL Study",
    "objective": "To assess perceptions of FedEx as a UEFA Champions League sponsor and identify fan expectations for sponsor engagement in selected markets."
  },
  "coverMode": "compact",
  "headline": "FedEx faces mixed perceptions as UCL sponsor",
  "hero": {
    "mode": "tension",
    "primary": {
      "value": "33.6%",
      "label": "Strong natural fit",
      "detail": "92 of 274 responses",
      "emphasis": true
    },
    "tension": {
      "value": "31%",
      "label": "Relevant but unclear",
      "detail": "85 of 274 responses",
      "emphasis": true
    },
    "gap": {
      "value": "2.6pp",
      "caption": "separates them"
    },
    "note": "Dual perceptions highlight a challenge for FedEx."
  },
  "whatWeFound": "FedEx is seen as a natural fit for the UEFA Champions League by many, yet a notable portion finds its sponsorship unclear or unnoticed. This highlights a dual perception challenge across different markets.",
  "modules": [
    {
      "kind": "distribution",
      "question": "FedEx as a Champions League sponsor?",
      "n": 274,
      "options": [
        {
          "label": "Strong natural fit",
          "count": 92,
          "pct": 33.6,
          "highlight": true
        },
        {
          "label": "Relevant but unclear",
          "count": 85,
          "pct": 31,
          "highlight": true
        },
        {
          "label": "Mostly brand visibility",
          "count": 29,
          "pct": 10.6,
          "highlight": false
        },
        {
          "label": "Never noticed them",
          "count": 68,
          "pct": 24.8,
          "highlight": false
        }
      ]
    }
  ],
  "bottomLine": {
    "text": "FedEx must address varied perceptions to strengthen sponsorship impact.",
    "form": "tension"
  },
  "methodology": "274 completed responses · 4 markets · 2 surveys",
  "footerTagline": "Fan insight. Smarter strategy. Stronger impact.",
  "richness": "standard"
} as ExecutiveReportDocument;
export const fedexEvidenceDocument: EvidenceReportDocument | null = {
  "kind": "studio-evidence-report-v1",
  "masthead": {
    "brand": "FANOMETRIX",
    "kicker": "Survey Study Report"
  },
  "identity": {
    "title": "FedEx UCL Study"
  },
  "eyebrow": "Evidence & opportunity",
  "headline": "FedEx's sponsorship impact varies across markets",
  "intro": "The evidence reveals varying perceptions of FedEx's sponsorship across different countries, with visibility and clarity issues presenting the clearest opportunities for improvement.",
  "modules": [
    {
      "kind": "segment-comparison",
      "mode": "leaders",
      "caption": "Most-selected answer by market",
      "points": [
        {
          "label": "France",
          "pct": null,
          "value": "Strong natural fit"
        },
        {
          "label": "Germany",
          "pct": null,
          "value": "Never noticed them"
        },
        {
          "label": "Spain",
          "pct": null,
          "value": "Relevant but unclear"
        },
        {
          "label": "the UK",
          "pct": null,
          "value": "Strong natural fit"
        }
      ]
    },
    {
      "kind": "ranked-distribution",
      "question": "How could FedEx help fans most?",
      "n": 274,
      "options": [
        {
          "label": "Access to experiences",
          "pct": 32.8,
          "count": 90,
          "highlight": true
        },
        {
          "label": "Connecting football fans",
          "pct": 24.5,
          "count": 67,
          "highlight": true
        },
        {
          "label": "Supporting local communities",
          "pct": 21.5,
          "count": 59,
          "highlight": false
        },
        {
          "label": "Exclusive football content",
          "pct": 21.2,
          "count": 58,
          "highlight": false
        }
      ],
      "leadNote": "“Access to experiences” leads by 8.3pp"
    }
  ],
  "implications": [
    "FedEx may want to consider enhancing visibility in Germany, where many have never noticed them.",
    "Clarifying the sponsorship's relevance in Spain could address the 'Relevant but unclear' perception.",
    "FedEx may want to focus on enhancing fan experiences to improve sponsorship perception."
  ],
  "methodology": "274 completed responses · 4 markets · 2 surveys",
  "footerTagline": "Fan insight. Smarter strategy. Stronger impact."
} as EvidenceReportDocument | null;
export const fedexReportComplete = true;
