// AUTO-GENERATED by lib/studio/qa/fedex-report-generate.ts — a real editorial report composed
// from the live FedEx approved Findings. Preview-only; the production path persists to study_reports.
import type { StudyReportDocument } from "@/lib/studio/report/report-document";
export const fedexPreviewDocument: StudyReportDocument = {
  "kind": "studio-report-document-v1",
  "title": "FedEx UCL Sponsorship Perception and Engagement Strategies",
  "objective": "To assess perceptions of FedEx as a UEFA Champions League sponsor and identify fan expectations for sponsor engagement in selected markets.",
  "coverMode": "compact",
  "meta": {
    "totalResponses": 274,
    "markets": [
      "France",
      "Germany",
      "Spain",
      "the UK"
    ],
    "surveys": 2
  },
  "pages": [
    {
      "archetype": "executive",
      "kicker": "Executive summary",
      "chapter": "01",
      "headline": "Credible fit is undermined by inconsistent recognition across markets",
      "interpretation": "FedEx is perceived as a strong natural fit for the UEFA Champions League by a plurality of respondents. However, a significant portion finds its sponsorship unclear or unnoticed, with perceptions varying by country. This inconsistency suggests a need for FedEx to enhance visibility and tailor engagement strategies to improve recognition and relevance.",
      "modules": [
        {
          "kind": "key-numbers",
          "stats": [
            {
              "value": "31%",
              "label": "Relevant but unclear",
              "detail": "85 of 274"
            },
            {
              "value": "24.8%",
              "label": "Never noticed them",
              "detail": "68 of 274"
            },
            {
              "value": "10.6%",
              "label": "Mostly brand visibility",
              "detail": "29 of 274"
            }
          ]
        }
      ]
    },
    {
      "archetype": "audience-comparison",
      "kicker": "By audience",
      "chapter": "02",
      "headline": "FedEx's sponsorship perception varies across markets",
      "interpretation": "Perceptions of FedEx as a UCL sponsor differ by country, with 'Strong natural fit' leading in France and the UK, while 'Never noticed them' is more common in Germany, and 'Relevant but unclear' in Spain.",
      "modules": [
        {
          "kind": "audience-comparison",
          "caption": "Most-selected answer by market",
          "points": [
            {
              "label": "France",
              "pct": null,
              "value": "Strong natural fit"
            },
            {
              "label": "Germany",
              "pct": null,
              "value": "Never noticed them"
            },
            {
              "label": "Spain",
              "pct": null,
              "value": "Relevant but unclear"
            },
            {
              "label": "the UK",
              "pct": null,
              "value": "Strong natural fit"
            }
          ]
        }
      ]
    },
    {
      "archetype": "key-numbers",
      "kicker": "The evidence",
      "chapter": "03",
      "headline": "Enhancing fan experiences can improve sponsorship perception",
      "interpretation": "Fans prefer 'Access to experiences' as the primary way FedEx could enhance its sponsorship role. This suggests focusing on fan experiences could address areas where the sponsorship is unclear or unnoticed.",
      "modules": [
        {
          "kind": "insight-text",
          "text": "Fans prefer 'Access to experiences' as the primary way FedEx could enhance its sponsorship role. This suggests focusing on fan experiences could address areas where the sponsorship is unclear or unnoticed."
        }
      ]
    },
    {
      "archetype": "key-numbers",
      "kicker": "The evidence",
      "chapter": "04",
      "headline": "FedEx's sponsorship visibility needs improvement",
      "interpretation": "A significant portion of respondents have never noticed FedEx as a sponsor, indicating a need for enhanced visibility and clearer messaging about its role in the UEFA Champions League.",
      "modules": [
        {
          "kind": "hero-stat",
          "stat": {
            "value": "24.8%",
            "label": "Never noticed them",
            "detail": "68 of 274 responses",
            "emphasis": true
          }
        }
      ]
    },
    {
      "archetype": "implications",
      "kicker": "Implications",
      "chapter": "05",
      "headline": "What this means",
      "modules": [
        {
          "kind": "implications",
          "items": [
            "Tailor engagement strategies to different markets to enhance sponsorship recognition.",
            "Focus on providing fan experiences to align with expectations and improve perception.",
            "Enhance visibility and clarify FedEx's sponsorship role through targeted marketing."
          ]
        },
        {
          "kind": "methodology",
          "lines": [
            "274 completed responses across France, Germany, Spain, the UK.",
            "FedEx UCL Sponsorship 26/27 - Survey (196) · FedEx UCL Sponsorship 26/27 - Survey v2 (78)",
            "Findings are human-curated; every figure is a governed survey result. Percentages are of completed responses per question."
          ]
        }
      ]
    }
  ]
} as StudyReportDocument;
