// AUTO-GENERATED by lib/studio/qa/fedex-page1-generate.ts — a real governed Executive page
// composed from the live FedEx approved Findings. Preview-only.
import type { ExecutiveReportDocument } from "@/lib/studio/report/executive-page";
export const fedexPage1Document: ExecutiveReportDocument = {
  "kind": "studio-exec-report-v1",
  "masthead": {
    "brand": "FANOMETRIX",
    "kicker": "Survey Study Report"
  },
  "identity": {
    "title": "FedEx UCL Study",
    "objective": "To assess perceptions of FedEx as a UEFA Champions League sponsor and identify fan expectations for sponsor engagement in selected markets."
  },
  "coverMode": "compact",
  "headline": "FedEx's UCL Sponsorship Faces Perception Challenges",
  "hero": {
    "mode": "tension",
    "primary": {
      "value": "33.6%",
      "label": "Strong natural fit",
      "detail": "92 of 274 responses",
      "emphasis": true
    },
    "tension": {
      "value": "31%",
      "label": "Relevant but unclear",
      "detail": "85 of 274 responses",
      "emphasis": true
    },
    "gap": {
      "value": "2.6pp",
      "caption": "separates them"
    },
    "note": "Mixed perceptions highlight clarity and visibility issues."
  },
  "whatWeFound": "FedEx is seen as a natural fit for the UEFA Champions League, yet many fans find its sponsorship unclear or unnoticed. This indicates a mixed perception across different markets.",
  "modules": [
    {
      "kind": "distribution",
      "question": "FedEx as a Champions League sponsor?",
      "n": 274,
      "options": [
        {
          "label": "Strong natural fit",
          "count": 92,
          "pct": 33.6,
          "highlight": true
        },
        {
          "label": "Relevant but unclear",
          "count": 85,
          "pct": 31,
          "highlight": true
        },
        {
          "label": "Mostly brand visibility",
          "count": 29,
          "pct": 10.6,
          "highlight": false
        },
        {
          "label": "Never noticed them",
          "count": 68,
          "pct": 24.8,
          "highlight": false
        }
      ]
    }
  ],
  "bottomLine": {
    "text": "FedEx must address visibility and clarity to strengthen sponsorship impact.",
    "form": "implication"
  },
  "methodology": "274 completed responses · 4 markets · 2 surveys",
  "footerTagline": "Fan insight. Smarter strategy. Stronger impact.",
  "richness": "standard"
} as ExecutiveReportDocument;
