"use client";

// Slice B preview — the live-composed FedEx TWO-PAGE infographic report, rendered through the
// real production components (Executive page A.4 + Evidence page). Generated by
// lib/studio/qa/fedex-infographic-generate.ts. No hand-authored data.
import { ExecutiveReportPage } from "@/app/components/studio/report/ExecutiveReportPage";
import { EvidenceReportPage } from "@/app/components/studio/report/EvidenceReportPage";
import { fedexExecutiveDocument, fedexEvidenceDocument, fedexReportComplete } from "../fedex-infographic-config";

export default function FedexInfographicPreview() {
  return (
    <div>
      <div data-no-print="true" style={{ display: "flex", gap: 12, alignItems: "center", padding: "10px 20px", borderBottom: "1px solid #E3E6EA", fontFamily: "system-ui", fontSize: 13, background: "#fff" }}>
        <span style={{ color: "#858D99" }}>FedEx infographic report · {fedexEvidenceDocument ? "2 pages" : "1 page"} · {fedexReportComplete ? "story complete" : "story continues"}</span>
        <button type="button" onClick={() => window.print()} style={{ marginLeft: "auto", border: "1px solid #D7B87A", background: "transparent", color: "#8A6D2F", borderRadius: 6, padding: "4px 12px", fontSize: 12.5, cursor: "pointer" }}>Print / PDF</button>
      </div>
      <div style={{ padding: "24px 0 8px", background: "#F4F5F7" }}>
        <ExecutiveReportPage doc={fedexExecutiveDocument} />
      </div>
      {fedexEvidenceDocument && (
        <div style={{ padding: "8px 0 24px", background: "#F4F5F7" }}>
          <EvidenceReportPage doc={fedexEvidenceDocument} />
        </div>
      )}
    </div>
  );
}
